name: CI (test & build only)

on:
  push:
    branches: ['**']        # 모든 브랜치
    tags-ignore: ['*']      # (옵션) 태그 푸시는 제외
  pull_request:
    branches: ['**']        # 모든 브랜치 대상 PR
  workflow_dispatch: {}     # (옵션) 수동 실행

permissions:
  contents: read

env:
  NODE_VERSION: 20

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install deps
        run: npm ci

      # 빌드만 수행(산출물 업로드/릴리스 없음)
      - name: Build
        run: npm run build --if-present
