name: CI (test & build only)

on:
  push:
  pull_request:

permissions:
  contents: read

env:
  NODE_VERSION: 20

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install deps
        run: npm ci

      # 빌드만 수행(산출물 업로드/릴리스 없음)
      # 네 프로젝트에 build 스크립트가 없고 deploy만 있다면, 아래 줄을 deploy로 바꿔도 되지만
      # “이미지는/아티팩트는 안 만든다”가 목적이면 build만으로 충분.
      - name: Build
        run: npm run build --if-present
